name: Deploy to stg env
on:
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: .

env:
  AWS_ACCOUNT_ID: ""
jobs:
  deploy-stg:
    runs-on: [batchv1, PDDXP000001, cpu-2, memory-4]
    permissions:
      contents: read
      id-token: write
    timeout-minutes: 15

    environment:
      name: stg
    env:
      ECR_REPOSITORY: "restful-app"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set docker IMAGE_TAG
        run: |
          echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV
          echo "$IMAGE_TAG"